@CrudDemoAPI_HostAddress = https://localhost:7055

GET {{CrudDemoAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{CrudDemoAPI_HostAddress}}/api/products
Content-Type: application/json

{
  "Name": "Makita",
  "Description": "A Makita é referência em ferramentas elétricas, a bateria e a combustão, atendendo diversos segmentos como construção civil, indústria automotiva e marcenarias.",
  "Price": 8000
}

###

GET {{CrudDemoAPI_HostAddress}}/api/customers

###
// POST CUSTOMER
POST {{CrudDemoAPI_HostAddress}}/api/customers
Content-Type: application/json

{
  "Name": "Makachera",
  "Email": "islam@email.com",
  "Cpf": "12345678900",
  "Address": "Rua das Flores, 123, São Paulo, SP, 01234-567",
  "IsBlocked": true
}

###
// GET CUSTOMER BY ID
@getId=3
GET {{CrudDemoAPI_HostAddress}}/api/customers/{{getId}}

###
// PUT CUSTOMER
@putId=3
PUT {{CrudDemoAPI_HostAddress}}/api/customers/{{putId}}
Content-Type: application/json
{
  "Id": {{putId}},
  "Name": "Moicanso",
  "Email": "moicalvo@gmail.com",
  "Cpf": "98765432100",
  "Address": "Avenida Paulista, 1000, São Paulo, SP, 01310-100"
}
###
//DELETE CUSTOMER
@id=2
DELETE {{CrudDemoAPI_HostAddress}}/api/customers/{{id}}

###
