@CrudDemoAPI_HostAddress = https://localhost:7055

GET {{CrudDemoAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{CrudDemoAPI_HostAddress}}/api/products
Content-Type: application/json

{
  "Name": "Makita",
  "Description": "A Makita é referência em ferramentas elétricas, a bateria e a combustão, atendendo diversos segmentos como construção civil, indústria automotiva e marcenarias.",
  "Price": 8000
}

###

GET {{CrudDemoAPI_HostAddress}}/api/customers

###
// POST
POST {{CrudDemoAPI_HostAddress}}/api/customers
Content-Type: application/json

{
  "Name": "Moicalvo",
  "Email": "moicalvo@gmail.com"
}

###
// GET by id
@id=2
GET {{CrudDemoAPI_HostAddress}}/api/customers/{{id}}

###
// PUT
@id=2
PUT {{CrudDemoAPI_HostAddress}}/api/customers/{{id}}
Content-Type: application/json
{
  "Id": {{id}},
  "Name": "Moicalvo",
  "Email": "moicalvo@gmail.com"
}
###
@id=2
DELETE {{CrudDemoAPI_HostAddress}}/api/customers/{{id}}

###
